sudo: required

services:
  - docker

before_install:
  - docker build -t vishalshah-comp/docker-react-app -f Dockerfile.dev .

script: 
  - docker run vishalshah-comp/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-app"
  env: "docker-app-env-prod"
  bucket_name: "elasticbeanstalk-ca-central-1-962269370162"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"