sudo: required

services:
  - docker

before_install:
  - docker build -t vishalshah-comp/docker-react-app -f Dockerfile.dev .

script: 
  - docker run vishalshah-comp/docker-react-app npm run test -- --coverage